### ISSUE TITLE
Grafana 8 compatibility

### ISSUE THREAD

**Issue by BWibo** [linksmart/grafana-sensorthings-datasource#56] opened 2021-08-11 10:26 UTC
Hey there, 

up front, thx for your great work, I'm using you SensorThingsAPI plugin a lot and really like it.

I just updated my Grafana to `v8.1.1` and found the the datasource is apparently having some problems 
with Grafana version `>v8`.

Here is a reproducible example using Docker:

Create a folder with a copy from the `docker-compose.yml` listed below and run `docker-compose up` from the folder:

```yml
version: '3'

# Volumes ---------------------------------------------------------------------
volumes:
  grafana_data:
    # external: true
  grafana_config:
    # external: true

services:
# Grafana -------------------------------------------------------------------
  grafana:
    image: grafana/grafana:8.1.1
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana
    ports:
      - 3000:3000/tcp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", 'bash', '-c', 'wget -S "http://127.0.0.1:3000/api/health" |& grep "200 OK"']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      GF_SERVER_ROOT_URL: "http://localhost:3000"
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,
        grafana-worldmap-panel,marcusolsson-json-datasource
        ,https://github.com/linksmart/grafana-sensorthings-datasource/archive/refs/tags/v1.4.0.zip;linksmart-sensorthings-datasource"
      # Allow unsigned plugins
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "linksmart-sensorthings-datasource"
      # Admin user
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
```

As shown in the log, Grafana is setting up the plugin and starting with no error.

When I add a Datasource using the plugin, everything seems fine aswell. I get the "Datasrouce is working" notification.
Finally, when I want to use the Datasource in a Dashboard, nothing is happening and the Browser log shows this:

![err](https://user-images.githubusercontent.com/7643434/129013466-785d82cb-58d0-45aa-8b27-136ffe902133.png)

**Comment by farshidtz** [comment] 2021-08-13 08:54
Thanks for reporting this issue. I see that you have re-submitted the issue on the new project: https://github.com/FraunhoferIOSB/frost-sensorthings-datasource/issues/6 

I'll go ahead and close it here.

**Closed by farshidtz** 2021-08-13 08:54 UTC

**Comment by farshidtz** [comment] 2021-08-13 10:23
For now, you could check if the latest version on master branch works: https://github.com/linksmart/grafana-sensorthings-datasource#install-the-latest-build-from-source

**Comment by BWibo** [comment] 2021-08-13 11:50
I just tried the last version, but I think the content of is almost the same on `master` and `v1.4.0`. `git diff master v1.4.0` returns this:
I get same error as reported above too.
```
index b5915c2..809a79a 100644
--- a/README.md
+++ b/README.md
@@ -1,6 +1,4 @@
 # Grafana OGC SensorThings Plugin
-**NOTE: This plugin is no longer maintained by LinkSmart. Please visit [frost-sensorthings-datasource](https://github.com/FraunhoferIOSB/frost-sensorthings-datasource).**
-
 A Grafana Data Source plugin to query observation and location data from an [OGC SensorThings](https://github.com/opengeospatial/sensorthings) server for visualization on [Grafana](http://grafana.org/) panels.

 It provides:
diff --git a/package-lock.json b/package-lock.json
index 9de6dd4..6d39db9 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -2404,9 +2404,9 @@
       "integrity": "sha1-Yzwsg+PaQqUC9SRmAiSA9CCCYd4="
     },
     "ini": {
-      "version": "1.3.7",
-      "resolved": "https://registry.npmjs.org/ini/-/ini-1.3.7.tgz",
-      "integrity": "sha512-iKpRpXP+CrP2jyrxvg1kMUpXDyRUFDWurxbnVT1vQPx+Wz9uCYsMIqYuSBLV+PAaZG/d7kRLKRFc9oDMsH+mFQ==",
+      "version": "1.3.5",
+      "resolved": "https://registry.npmjs.org/ini/-/ini-1.3.5.tgz",
+      "integrity": "sha512-RZY5huIKCMRWDUqZlEi72f/lmXKMvuszcMBduliQ3nnWbx9X/ZBQO7DijMEYS9EhHBb2qacRUMtC7svLwe0lcw==",
       "dev": true
     },
     "interpret": {
```

**Comment by farshidtz** [comment] 2021-08-13 12:39
> I think the content of is almost the same on master and v1.4.0

Correct. But v1.4.0 is not released on Grafana store. Version v1.4.0 is same as master on Github.

Grafana 8 enfoces plugin signing. You need to disable that for this plugin to make it work:
Try set this environment variable:
```
GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=linksmart-sensorthings-datasource
```

EDIT: Apologies. I just saw you were already taking v1.4.0 and setting the above env variable in your docker compose script. I don't know what the issue is. Let's wait for an answer on https://github.com/FraunhoferIOSB/frost-sensorthings-datasource/issues/6
